package com.sekretowicz.workload_service.model;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.index.TextIndexed;
import org.springframework.data.mongodb.core.mapping.Document;

import java.util.List;

@Document(collection = "trainer_summaries")
@Data
@NoArgsConstructor
@AllArgsConstructor
public class TrainerSummary {
    @Id
    private String id;
    private String username;

    @TextIndexed
    private String firstName;

    @TextIndexed
    private String lastName;

    private Boolean status;
    private List<YearSummary> years;

    @Override
    public boolean equals(Object obj) {
        if (this == obj) return true;
        if (obj == null || getClass() != obj.getClass()) return false;

        TrainerSummary that = (TrainerSummary) obj;

        //Probably we shouldn't compare IDs, as they are generated by MongoDB
        if (!username.equals(that.username)) return false;
        if (!firstName.equals(that.firstName)) return false;
        if (!lastName.equals(that.lastName)) return false;
        if (!status.equals(that.status)) return false;
        return years.equals(that.years);
    }
}
