server:
  port: 8081

spring:
  application:
    name: workload-service
  activemq:
    user: admin
    password: admin
    broker-url: tcp://localhost:61616

jwt:
  secret: veryStrongSecretKeyForJwtGeneration1234567890