server:
  port: 8081

spring:
  activemq:
    user: admin
    password: admin
    broker-url: tcp://172.17.0.2:61616

  data:
    mongodb:
      host: 172.17.0.3
      port: 27017
      database: trainer_summary_db