server:
  port: 8081

spring:
  application:
    name: workload-service
  activemq:
    user: admin
    password: admin
    broker-url: tcp://localhost:61616
  data:
    mongodb:
      host: localhost
      port: 27017
      database: trainer_summary_db